version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
