version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  app:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file: .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Configuración para desarrollo
    stdin_open: true
    tty: true

volumes:
  db-data:
